### PR TITLE
Add info about DFPWM support in FFmpeg

### PR DESCRIPTION
**Pull request by MCJack123**
This PR adds some documentation about the recently added support for DFPWM audio in FFmpeg.

### CODE REVIEW

**Comment by SquidDev** [comment]
I kinda wonder if it's just worth waiting until a new ffmpeg version is released.

**Comment by MCJack123** [comment]
I don't see that happening until at least September, considering the last release just came out three months ago and they average just over one release per year.

**Comment by SquidDev** [comment]
Ahh fair enough. Maybe worth moving this later in the list then. I'm trying to list the recommended (or at least easiest) method first, and using a dev version of ffmpeg is definitely not that :p.

**Comment by SquidDev** [comment]
It's out!

**Pull request closed without merging**
