### PR TITLE
fix models

### PR DESCRIPTION
**Pull request by magiczocker10**

### CODE REVIEW

**Comment by SquidDev** [comment]
Thanks for the contribution!

Can you post a before and after screenshot of the models? I'm not entirely sure what was broken about them which needed fixing.

**Comment by magiczocker10** [comment]
Some textures were wrong rotated in comparison to the original before the rewrite to json some years ago.

**Comment by magiczocker10** [comment]
Minecraft 1.1 were Turtles are introduced:
MC 1 1

Minecraft 1.14.4 were some textures are wrong rotated:
MC 1 14 4

**Comment by SquidDev** [comment]
Thank you very much!

**Pull request merged**
