### PR TITLE
Additional terminal buttons

### PR DESCRIPTION
**Pull request by SquidDev**
Following on from my comments in #51, I had a look at adding a sidebar to computer GUIs. There's a couple of reasons I think some form of this is worth adding:

 - Better discoverability of features. It's not obvious that <kbd>Ctrl+T</kbd> terminates a program, and <kbd>Ctrl+R</kbd> can be used to reboot. Having buttons to do so makes it a little more friendly.
 - More flexibility in the future. This is a more distant plan, but I'd quite like to add a button to upload/download a file (circumventing pastebin) and potentially an in-game docs browser, and we need an easy way to get to them.

While this PR is still a work in progress, the UI is in a state where I'd quite like some feedback on it. Any and all feedback is welcome - UX is not my strong point, so would definitely like this to a) look good and b) be intuitive.

The computer GUI with a new sidebar

### CODE REVIEW

**Comment by Lemmmy** [comment]
Assuming the shortcuts Ctrl+T and Ctrl+S/R are hardcoded (if I remember correcrtly, they are), perhaps it's worth adding them to the tooltips for those buttons to increase the discoverability of features.

Something like `Stop the currently running code (hold Ctrl+T)`:
https://github.com/SquidDev-CC/CC-Tweaked/pull/809/files#diff-503dd38b9e07366621b83c3054b514f5c5af590d6c1b43ffb35f676c703ebb74R114-R116

**Comment by Merith-TK** [comment]
This looks great! one suggestion I have, is allow peripherals to define a button to be added, which then gets appended below the power buttons as its own tab? 

also im trying to figure out how complicated this would be to implement in fabric... might take a bit

**Comment by SquidDev** [comment]
> Allow peripherals to define a button to be added, which then gets appended below the power buttons as its own tab?

This would be neat, but possibly not something I want quite yet. Not sure what peripherals would want it for.

> Trying to figure out how complicated this would be to implement in fabric...

It _should_ be pretty simple - everything we're using here is core Minecraft, so the only changes needed should be mappings ones.

**Comment by Merith-TK** [comment]
> It _should_ be pretty simple - everything we're using here is core Minecraft, so the only changes needed should be mappings ones.

keyword, *should*, would love for it to be a simple import,

**Pull request merged**
