### PR TITLE
Make the key for mtime "modified" in fs.attributes

### LINKED ISSUE #511: "Modification" key in fs.attributes is inconsistent with docs
Docs say: [modified](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/src/main/java/dan200/computercraft/core/apis/FSAPI.java#L470)
Code does: [modification](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/src/main/java/dan200/computercraft/core/apis/FSAPI.java#L481)

### PR DESCRIPTION
**Pull request by plt-hokusai**
Just like the docs say!

Fixes #511. See also: #513

### CODE REVIEW

**Comment by JakobDev** [comment]
fs.attributes() is in CCT for a while now and some programs are already using it. Chancing the key will break compatibility without any benefit. It's way better to just change the documentation.

**Comment by plt-hokusai** [comment]
Changing the documentation doesn't fix the issue of consistency, now, does it? One is `created`, while the other is `modified`. The options should be `modified` and `created` or `modification` and `creation`, _not_ a mix!

**Comment by dmarcuse** [comment]
Clearly the best solution is to instead have four keys, `created`, `creation`, `modified`, and `modification`

**Comment by SquidDev** [comment]
I think we should add an `__index` meta method which does Levenshtein distance to find the correct key. 

Or just add `modified` and `modification`.

**Pull request merged**
