### PR TITLE
Anonymized GPS

### PR DESCRIPTION
**Pull request by osmarks**
I've made GPS generate a random reply channel for each ping, so that things can't be tracked by ID if they send GPS requests a lot, and to avoid hitting the channel limit if for some reason a computer has a very high ID.

### CODE REVIEW

**Comment by SquidDev** [comment]
One problem I see with this is that there is now no guarantee that the received message is for this computer. It's possible that two computers will open the same channel, and thus receive conflicting information.

I feel a better solution would be to send _and_ receive on `CHANNEL_GPS`, and then tag each message with a random "query id".

**Comment by osmarks** [comment]
I don't *think* conflicting information is actually a problem, as a correctly-functioning GPS server should send the same position information in response to all requests, and the distances will be different per-receiver anyway.

**Comment by SquidDev** [comment]
That's true. Perhaps we don't need the ID at all then, and can just operate on `CHANNEL_GPS`?

**Comment by osmarks** [comment]
Possibly, though the current channel-based way does slightly reduce the amount of work GPS hosts and clients have to do.

**Comment by SquidDev** [comment]
Eh, I don't think the overhead is too big of a concern here. I'm happy to reuse a channel if it avoids us tramping over the main rednet channel space.

**Comment by osmarks** [comment]
I'm not sure about putting it on the existing channel, as it may require a change to the existing GPS host programs, I'll check.

**Comment by SquidDev** [comment]
And merged, thank you very much!

**Pull request merged**
