### PR TITLE
Add iris to Shader Mod check

### LINKED ISSUE #1967: issues with shaders
### Minecraft Version

1.21.x

### Version

1.113.0

### Details

hi there i spoke with the guys on the iris discord as having an issue when shaders enabled the advanced screens in a multiple config  glitches out real bad they suggested to log with you guys to see if it can be fixed
Screenshot 2024-09-05 175019

### PR DESCRIPTION
**Pull request by maxnoller**
Added iris to shader mod check

Fixes #1967

### CODE REVIEW

**Comment by Hex4dec** [comment]
~~Are you sure this is the correct fix? Note that you are adding the check to the Forge project, and Oculus is the Forge version of Iris. This shouldn't do anything.~~

Nevermind, seems like Iris natively supports NeoForge.

**Comment by maxnoller** [comment]
I tested this in the ATM10 Modpack Alpha that uses Neoforge and Iris (I encountered the bug there) and this one line change fixed the problems and so far I have been playing for 4 hours with it and have not noticed any problems. I haven't touched MC modding in a long time so im not sure this is all that is needed. Also regarding the failed test, I dont think my code change caused this right? Should I still look into fixing that?

**Comment by Hex4dec** [comment]
No, pretty sure CC:T tests are a mess.

**Comment by piprett** [comment]
>  (-14930832, -60, -4764970) Moved 32 items into a double chest
> Expected: [<32>]
> but: was null at -14930830,-58,-4764968 (relative: 2,2,2) (t=6)

Looks like a flaky test - not your fault.

**Comment by SquidDev** [comment]
Thank you for the PR! I'm afraid I ended up fixing this in a slightly different way (63181e73a14f840a360125e1e6b2be8907d551f3) — we no longer need the Oculus check at all, as Oculus doesn't support MC 1.21.

**Comment by maxnoller** [comment]
okey that looks like a slightly more comprehensive way to deal with this issue than what I did. Thanks for dealing with this os fast, now I can finally create Bar-Chart galore in Minecraft again

**Pull request closed without merging**
