### PR TITLE
Update edit.lua with my version

### PR DESCRIPTION
**Pull request by TagFreettle**

### CODE REVIEW

**Comment by SquidDev** [comment]
Hai, thanks for the contribution. As the README says, my general stance here is for people to PR against the original CC repo if at all possible, and I'll merge it across. 

This means more people have an opportunity to comment, and there's a greater chance of your changes getting into the original mod.

**Comment by TagFreettle** [comment]
What? What happened?

**Comment by TagFreettle** [comment]
But I sent a pull request already and it never came through. What happened?

**Comment by vpontin** [comment]
Link that pull request here and i think Squid can analyse

**Pull request closed without merging**
