### PR TITLE
Add curl as alias for wget

### PR DESCRIPTION
**Pull request by JakobDev**
curl is also a well known downloader.

### CODE REVIEW

**Comment by SquidDev** [comment]
`curl` and `wget` have similar purposes, but are very different programs and operate very differently. I don't think it's fair or accurate to alias the two.

**Comment by JakobDev** [comment]
@SquidDev Thats right, but the must people just run wget <url> or curl <url> to download a file.

**Comment by Lemmmy** [comment]
curl isn't a downloader, `curl https://example.com` doesn't download the file, it outputs it to stdout. To save it, you'd have to use the `-O` option, or redirect stdout to a file, e.g. `curl -O https://example.com` or `curl https://example.com > example.com`

**Comment by lupus590** [comment]
Could curl be a stub program which just prints "you probably want wget [URL] [filename]"

**Pull request closed without merging**
