### PR TITLE
Added interaction when turtle places empty bucket on cauldron.

### PR DESCRIPTION
**Pull request by IICarst**
Fix for this issue: https://github.com/cc-tweaked/CC-Tweaked/issues/1008

### CODE REVIEW

**Comment by dathide** [comment]
Looks good to me, hope this gets merged soon!

**Review by dathide — CHANGES_REQUESTED** [review]
This would allow BoatItem, WaterLilyBlockItem, and BottleItem to be used on cauldrons just like buckets.

**Comment by IICarst** [comment]
I added an condition to make sure only buckets can be used.

**Comment by SquidDev** [comment]
Thank you for the PR. I'm afraid this isn't something I really want to special case.

**Pull request closed without merging**
