### PR TITLE
Computers no longer keep IDs 

### PR DESCRIPTION
**Pull request by 99-lives**
See #504 for discussion and justification. Happy to continue the discussion in that issue if you aren't convinced.

1. Unlabeled computers and turtles no longer keep their IDs when broken, reverting the behavior introduced in #437.
2. CraftOS programs `edit`, `wget` and `pastebin get` now print a warning to the user after completion, if they are ran on an unlabeled computer.
3. Added a line to the label help doc explaining that unlabeled computers will lose their files.

My warning message is pretty wordy, so I'm happy to hear any other suggestions to slim it down.

Note that the code that displays computer IDs in inventory tooltips is still present, but as far as I'm aware, is now unused. I'm afraid I'm not familiar enough with this project to find and delete that code.

### CODE REVIEW

**Comment by Lupus590** [comment]
While I like the changes to the lua programs and think that that is a good idea along with extra docs about making sure that users don't accidentally lose data, I would prefer that there was a config option for preserving IDs.

**Comment by 99-lives** [comment]
Are you talking about a server wide config option in `computercraft-server.toml`? If so, the option could become a point of contention on multiplayer servers. But I supposed the same could be said about this whole patch. 

Would it be possible to make it a per-user setting? A command like `/computercraft keepid true` perhaps? This would affect every computer placed by the player, while leaving computers placed by turtles and other players unaffected. Unfortunately I lack the Forge or Java knowledge to implement this (I only created the Java patches using my experience with other languages, I don't actually know Java :laughing: )

Also is there something I can do to fix the license check in gradel? Like I said, I don't know Java.

**Comment by MCJack123** [comment]
> Also is there something I can do to fix the license check in gradel? Like I said, I don't know Java.

Looks like you just need to merge in `mc-1.15.x` into your branch. The CI checks have been updated to check for 2021, but your files were forked while they still were in 2020.

**Comment by 99-lives** [comment]
Thanks @MCJack123, that worked.

**Comment by SquidDev** [comment]
Thank you for your PR!

I'm afraid I'm not going to merge this. I really don't want to revert the changes to turtle drops, at least not wholesale. I've put a bit more explanation/rationale for the whole change in https://github.com/SquidDev-CC/CC-Tweaked/issues/504#issuecomment-756459791.

**Pull request closed without merging**
