### PR TITLE
feat: support PATCH

### PR DESCRIPTION
**Pull request by jaredallard**
**What this PR does**: Theoretically brings in `PATCH` support for HTTP. Need to verify, however.

### CODE REVIEW

**Comment by SquidDev** [comment]
Well, this is the new CI's first PR, so no surprise it's kinda broken. I'll look into 
it. 

I wonder if it'd be worth including `TRACE` there too? Not sure how I missed these two when doing the initial change.

**Comment by jaredallard** [comment]
@SquidDev it happens! It might be worth just allowing any method to be passed, a few services have their own custom HTTP methods. Unsure if the Java HTTP client will work with that though.

**Comment by SquidDev** [comment]
Sadly not - Netty [has a predefined list](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpMethod.java#L92) of HTTP request methods, and I don't believe we can use anything else.

**Comment by jaredallard** [comment]
OK, I've confirmed this PR is working (for my use-case anyways!)

**Pull request merged**
