### PR TITLE
An initial stab at documentation generation

### PR DESCRIPTION
**Pull request by SquidDev**
This is still heavily WIP, but the actual tooling is now at a stage where I think it's worth opening a pull request.

As discussed in #133, I want to bring a lot of documentation inline into the actual code of CC:Tweaked. Effectively, every public method will an associated doc comment.

### Documentation is currently [exported to tweaked.cc](https://tweaked.cc/).  Please have a read through, and check it makes sense!
As always, Do post below (or submit a PR) if you have any comments or suggestions.

## Motivation

There's a couple of reasons for this change:

 - Make the documentation easier to maintain _for me_, as you're rather forced to update the docs when making code changes.
 - The documentation is now version controlled, and so it should be much easier to host documentation for multiple/older versions.
 - As docs are generated by a computer, it means we have access to information in a more structured way (i.e: location of definition, argument counts, type hints, etc...). We don't do anything with this right now, but have ideas for the future.

That said, I realise this does make external contributions more difficult, as one has to submit PRs - I'd love to hear suggestions on how to make contributing easier.

## Todo list
There's a lot of things which still need to be done. Most of these should be pretty easy, just rather tedious, so please do submit PRs (or get in touch on Discord/IRC/Forums) if you'd like to help.

 - [ ] Document all the Java APIs (`term`, `redstone`, etc...). I'm planning to do this via a series of stub files in a `doc/stub` folder. Effectively, create another API-like Lua file, with empty functions for each API function.
 - [ ] Work out an effective way to document the bios, shell and multishell programs. The last two are especially odd.
 - [ ] Somewhat related, but add any other missing documentation. This can be found by removing the `-doc:undocumented -doc:undocumented-arg` line from `illuaminate.sexp` and re-running the linter.
 - [ ] Clean up examples (and work out a nice strategy for showing the expected output).
 - [ ] Fix any broken references.
 - [ ] Test! Documentation shouldn't break anything, but the build is currently failing so I've clearly done something.
 - [x]  > Abigail: could you add a link to source tho
 - [ ] Embed copy-cat in the documentation page. This is probably far more long term, but I'd really like to embed a basic emulator within the docs, to allow for basic "run this example" functionality. I'm not entirely sure how this'll integrate with everything else though, so may come much later.

### CODE REVIEW

**Comment by SquidDev** [comment]
This was meant to be a draft PR. Woops.

**Comment by ejm554** [comment]
This is great. Some random questions:

- What is the target audience for the documentation? Is it just developer and technical types, or will part of the documentation be aimed towards casual players who want to learn more?
- Can you help me understand better _where_ the documentation text that's visible on tweaked.cc is stored and/or _how_ it can be edited?
- Can documentation be done by a contributor without that contributor also being responsible for any other code? Or will code contributors essentially be the ones responsible for the documentation tasks? (Maybe this was touched on when you wrote, "I realise this does make external contributions more difficult.")
- Do you expect documentation that only exists elsewhere, e.g., on [wiki.computercraft.cc](https://wiki.computercraft.cc/), will be copied into the new system?
- Will the documentation that exists elsewhere be taken offline in favor of this new system, or do you envision having a few places where documentation exists ?
- Would it make sense to use videos as a form of documentation. I'm thinking as a supplement or alternative to written tutorials.

**Comment by SquidDev** [comment]
@ejm554 Thanks for the questions! Definitely some things I should have clarified, and some food for thought there too.

> What is the target audience for the documentation? Is it just developer and technical types, or will part of the documentation be aimed towards casual players who want to learn more?

This is definitely designed to be user-facing documentation, so something players will be able to use, rather than just for me. However, it's also intended as reference documentation - while it should give you an idea how what everything does/how to use it, it's not intended as a tutorial to CC.

> Can you help me understand better where the documentation text that's visible on tweaked.cc is stored and/or how it can be edited?

The easiest thing to do is probably just [look at the diff][diff]. If you scroll down beyond the first couple of files, it's just stored as doc-comments above each definition. See [`io.lua`][io] (or anything in the `rom/apis` folder) for an example.

We're basically using [LDoc-style doc comments][ldoc], which are then extracted and converted to HTML. Editing the documentation pretty much just boils down to editing the comments and rerunning the generation tool (which will happen on each commit when I finally set up the tooling for it).

> Can documentation be done by a contributor without that contributor also being responsible for any other code? Or will code contributors essentially be the ones responsible for the documentation tasks? (Maybe this was touched on when you wrote, "I realise this does make external contributions more difficult.")

Yep! I'll happily accept any PRs which only change documentation. Ideally any new changes will also include documentation too (when relavent), but we'll see how that pans out.

I guess my main concern with "I realise this does make external contributions more difficult." is that there's a much higher commitment in making a PR than a wiki edit. Even if you do it via GH's web interface, you've still got to open the PR, possibly respond to feedback, etc... rather than a wiki's immediate editing.

> Do you expect documentation that only exists elsewhere, e.g., on wiki.computercraft.cc, will be copied into the new system?

The current docs on tweaked.cc are pooled from a combination of the two wikis. That said, I don't want to pull everything. As #133 kinda touches on, the wiki is definitely more suited for long-form documentation (such as tutorials, guides, etc...).

I'd quite like to look into a system for automatically syncing information between the two, but that's much further down the line (and I need to talk a lot with the wiki admins).

> Will the documentation that exists elsewhere be taken offline in favor of this new system, or do you envision having a few places where documentation exists ?

Just to add to the above, definitely don't want to take down wiki.computercraft.cc. There's a lot of content (see, for instance [the additional comments on `require`][require]) which works much better on a wiki than in doc comments.

> Would it make sense to use videos as a form of documentation. I'm thinking as a supplement or alternative to written tutorials.

Probably, yes - I know there's been several relatively<sup>1</sup> popular YouTube tutorial series. _However_, producing videos in a reasonably engaging and informative manner (and keeping them up-to-date) does require a lot more time than I'm willing to dedicate (and is well outside my skill-set/comfort zone). That said, if someone does want to take out the challenge, I'd love to see the results!

---

Sorry for the horrifically long wall of text, hope it answered all your questions! If there's anything you'd like me to clarify (or just new questions), just say :).

<sup>1</sup>: Relative to CC's pretty small community at least :).

[io]: https://github.com/SquidDev-CC/CC-Tweaked/blob/feature/doc-gen/src/main/resources/assets/computercraft/lua/rom/apis/io.lua
[diff]: https://github.com/SquidDev-CC/CC-Tweaked/pull/360/files
[ldoc]: https://stevedonovan.github.io/ldoc/manual/doc.md.html
[require]: https://wiki.computercraft.cc/Require

**Comment by lupus590** [comment]
> What is the target audience for the documentation? Is it just for developer and technical types, or will part of the documentation be aimed towards casual players who want to learn more?

Based on looking at the [tweaked.cc](tweaked.cc) website, this documentation is made for people who are writing Lua programs which run on computers in-game.

> Can you help me understand better where the documentation text that's visible on tweaked.cc is stored and/or how it can be edited? I tried searching in this CC-Tweaked repository for the text in the Colors documentation, but I couldn't find a match.

There is a program in the build chain which reads the three dashed (---) comments in this pull request and converts the comments into a HTML web page. If you open the files changed tab at the top and scroll down to one of the Lua files you should be able to recognise the text in the Lua file on its documentation page.

> Can documentation be done by a contributor without that contributor also being responsible for any other code? Or will code contributors essentially be the ones responsible for the documentation tasks? (Maybe this was touched on when you wrote, "I realise this does make external contributions more difficult.")

I don't see any reason that anyone couldn't document someone else's code, I will expect that SquidDev will begin asking for people to update documentation when they change things though. The external contributions being more difficult bit is probably about how anyone who wants to update the documentation now has to make a pull request, which requires knowing how to use GitHub and having an account here.

> Do you expect documentation that only exists elsewhere, e.g., on wiki.computercraft.cc, will be copied into the new system?

I would expect some of it will be copied, but not all of it as some of the stuff on the wiki is to do with crafting and programming. This documentation is about the function/API and how to use it.

> Will the documentation that exists elsewhere be taken offline in favor of this new system, or do you envision having a few places where documentation exists ?

I don't see this happening, the wiki might see itself becoming more focused on things that this doesn't cover (crafting recipes,  programming tips, etc.)

> Would it make sense to use videos as a form of documentation? I'm thinking as a supplement or alternative to written tutorials.

The wiki might need this now actually. Some people don't learn well from reading.

**Comment by SquidDev** [comment]
> Edit: ninja'd

Sorry!

**Comment by SquidDev** [comment]
I realise I've done very few of the original todos, but I'd rather get this merged sooner rather than later. I haven't time to finish documenting everything else, and given the lack of response from other people, I think it's fair to say no one else does either.

**Pull request merged**
