### PR TITLE
add / to dir in list

### PR DESCRIPTION
**Pull request by Lupus590**
now monochromatic displays are less ambiguous when listing folders and files

### CODE REVIEW

**Comment by Lupus590** [comment]
Not managed to test this yet and got to have food.

**Comment by SquidDev** [comment]
Hrrrmrm. I'm not 100% sure how I feel about this. I don't know if this is just because I'm not used to it, but it does look a little odd.

The new `ls` command

Would appreciate other people's thoughts on this - you can try it out at https://copy-cat.squiddev.cc/gh/pull/656/.

I guess the alternative solution here would be just to use `colours.grey` (or even keep green) on non-advanced terminals. This way we still have some visual indicator. Thoughts?

**Comment by Lupus590** [comment]
Monochromatic green looked too similar to the white on my 1.16 play world, grey could work though.

It's probably unnecessary complication, but I could put it behind a setting.
`list.dir_disabiguator` with valid settings as `none`, `slash`, `colour` and `both`.

**Comment by Lupus590** [comment]
Removing the `term.color` check works and makes it obvious. I guess that things like that should have been changed when pallets were introduced.

**Comment by Seniorendi** [comment]
> Would appreciate other people's thoughts on this
Does not look bad, but i like it more without the /

**Comment by SquidDev** [comment]
Sorry for taking so long to reply to this (yay my terrible mental health and even worse procrastination).

I've pushed a change which makes folders light grey on normal computers. I think that's a happy compromise between this and doing nothing - still not really happy with the trailing slash.

**Pull request closed without merging**
