### PR TITLE
Simplify monitor TBO shader

### PR DESCRIPTION
**Pull request by Lignum**
Not sure how I missed this in the initial PR, but the fixed-function pipeline's MVP matrix is exposed as the built-in shader variable `gl_ModelViewProjectionMatrix`, there's no need to retrieve it ourselves. This saves us some uniforms and `glGetFloat` calls, which can incur some overhead.

### CODE REVIEW

**Comment by SquidDev** [comment]
Huh, that's neat. I had assumed the two were entirely separate.

**Comment by SquidDev** [comment]
Hrmrm. [This][1] and [this][2] seem to suggest that this functionality was removed in OpenGL 3.1. Is it safe to rely on these?

[1]: https://www.khronos.org/opengl/wiki/GLSL_:_recommendations#Built-in_Uniforms
[2]: https://www.khronos.org/opengl/wiki/OpenGL_Context#Context_types

**Comment by Lignum** [comment]
Half the API was removed in OpenGL 3.1, but it's still perfectly fine to use it if your context is created with the compatibility profile, which Minecraft is. This is perfectly standards compliant.

**Comment by SquidDev** [comment]
Thanks!

**Pull request merged**
