### PR TITLE
#1256: "shell.complete should quote filenames with spaces in them"

### PR DESCRIPTION
**Pull request by LeVoid**
Regarding issue #1256 

Added an optional parameter to Shell.complete(sLine, bFull):
-> if bFull is set to true, the function will return the full filenames of all files that start with sLine. It also quotes filenames if they have a space in them. Not supplying bFull has the same result as setting it to false.

This way you can choose which option to use and aren't tied to either one.

### CODE REVIEW

**Comment by Wojbie** [comment]
How would this interact with current shell autocompleting logic? Don't it expect to be given suffix?

**Comment by LeVoid** [comment]
> How would this interact with current shell autocompleting logic? Don't it expect to be given suffix?

Because the current logic only supplies the first argument (sLine), bFull is set to nil. So it won't return the full names.

Due to this, nothing about the current logic changes. The only time it changes the returned list is when you supply the bFull-argument manually.

**Comment by SquidDev** [comment]
The trouble with that is I'm not sure when this is actually useful. This isn't compatible with `read`, so I'm not sure when you'd be able to use this?

**Comment by walksanatora** [comment]
i still believe that the idea discussed in the mentioned issue is better
(support backslash escapes in shell and autocomplete)

**Pull request closed without merging**
