### PR TITLE
Mc 1.16.x

### PR DESCRIPTION
**Pull request by Flexico**
[CC-Tweaked-mc-1.16.x.zip](https://github.com/SquidDev-CC/CC-Tweaked/files/5844033/CC-Tweaked-mc-1.16.x.zip)
I think I'm doing this right...

[Edit] WAIT NO NOT 1.15 *facedesk*

### CODE REVIEW

**Comment by Lupus590** [comment]
1.15 is the right branch to make the pr against unless it's a 1.16 specific thing.

Also you should say what the PR does.

BTW, it looks like this PR is malformed, I assume that you are trying to do the crafting upgrade retexture.

**Comment by Flexico** [comment]
Yeah, that's what I'm trying to do! Please forgive my ignorance, I've never done this before. X3

**Comment by SquidDev** [comment]
Hey! Thank you for the PR, I'm going to close this one as I'm afraid it's pretty unsalvageable and leave a comment on #689 with some instructions.

**Comment by Flexico** [comment]
Ok, thanks~

**Pull request closed without merging**
