### PR TITLE
Allow lua REPL to warn about using local variables

### PR DESCRIPTION
**Pull request by lupus590**
`local varname = value` results in `varname` being inaccessible in the next REPL cycle
sometimes this is unintended and is the result of the user having good habits when writing programs

### CODE REVIEW

**Comment by plt-abigail** [comment]
`>  local x = 1`
just defeated your pattern

**Comment by lupus590** [comment]
> 
> 
> `> local x = 1`
> just defeated your pattern

works on ccemux, I didn't try in game

**Comment by lupus590** [comment]
I'm not surprised, this is my first go at lua patterns. I'm committing the fix now

**Comment by plt-abigail** [comment]
Detecting this with patterns is straight-up impossible.. Also, you put in a `5`, not a `%`. Also, my example wasn't the `>`, that's the repl prompt; It was the spaces.

**Comment by lupus590** [comment]
extra white space is valid lua though

or am I wrong on that?

**Comment by plt-abigail** [comment]
Yes, and the pattern you checked in at first didn't match that.
Do this one next: `print(); local x = 1`

**Comment by lupus590** [comment]
I still don't get what you were trying to chek with the `> local x = 1` one

**Comment by lupus590** [comment]
`print(); local x = 1` doesn't match, which I expected and I would say is desired behaviour as I would assume that the person knows what they are doing as that looks a little odd

**Comment by plt-abigail** [comment]
`local x` `local x, y` `local x, y = 1`

**Comment by MrGoose13** [comment]
Coming in a bit late but I don't think this issue is about catching every use of `local`, it's about catching a common mistake newbies make.

I'd recommend a simple pattern, no need to go overboard: `"^%s*local%s+[a-zA-Z_]"`

I made this mistake as a newbie and I'm assuming @lupus590 did, too. A little hint would have been helpful for sure.

**Comment by lupus590** [comment]
I'm now thinking that this might be better on [SquidDev-CC/mbs](https://github.com/SquidDev-CC/mbs).

**Comment by SquidDev** [comment]
Hrmr, it occurs to me actually that we should possibly accent the message. Perhaps make it yellow? Otherwise it ends up rather noisy:

This message being rather hard to read.

It's even worse on pocket computers. Curse your low resolution CC :D:.

**Comment by SquidDev** [comment]
image

It's still a little gross, especially on pocket computers, but I'm honestly not sure what to do about that. I've merged this for now, and will update if something occurs to me.

**Comment by exerro** [comment]
The pattern could just search for `local` anywhere in the input. Of course, this would match it in strings too, but as it's just a generic warning that explains a situation I don't think that's too bad. It's also pretty simple to check for things in strings if you wanted to disable that.

For the message, what do you think of this:
> To access a variable in multiple inputs, remove the `local` keyword.

It's a bit shorter and I think it gets the same point across.

screenshot of warning in an emulator at pocket size

**Comment by lupus590** [comment]
> The pattern could just search for `local` anywhere in the input.

I specifically didn't want to do this in case someone was defining a function which had its own variables which needed to be local.

I do like that shorter message though.

**Comment by Lemmmy** [comment]
If this were MBS, you could just piggyback off it's syntax highlighter

**Comment by exerro** [comment]
Other than effort, is there any reason for the built-in `lua` program not to be super fancy? Using a Lua-side parser would let it give better error messages, handle multiple lines of input, and maybe even remove locals in the input automatically.

**Comment by SquidDev** [comment]
As you say, effort (and licensing). The BSRocks REPL bundled a Lua parser, which allowed us to do multi-line input, and mbs has syntax highlighting. It's all possible, it's just a matter of someone finding time to do it.

**Pull request merged**
