### PR TITLE
Expose expect as a module

### PR DESCRIPTION
**Pull request by SquidDev**
This moves expect from the bios into a new `craftos.expect` module (using naming as discussed in #232), removing the internal `_G["~expect"]` definition. Aparently people were using this irrespective of the "don't use this" comment, so we need to find another solution.

While this does introduce some ugliness (having to load the module in weird ways for programs, duplicating the expect function in memory), it does allow people to use the function in a supported way, and removes the global ugliness.

### CODE REVIEW

**Comment by dmarcuse** [comment]
If people are already using it despite the whole `~expect` thing, it might as well be official I guess.

**Comment by lupus590** [comment]
Don't we have a modules folder in ROM? Couldn't it go in there?

Or am I misremembering?

**Comment by SquidDev** [comment]
@lupus590 That's exactly where it is.

**Comment by lupus590** [comment]
Once again I prove that I don't read things properly

**Comment by hugeblank** [comment]
> Aparently people were using this irrespective of the "don't use this" comment, so we need to find another solution.
Well [I](https://github.com/hugeblank/syssm/blob/master/startup.lua#L23) [feel](https://github.com/hugeblank/qs-cc/blob/master/src/icup.lua#L16) [targeted](https://github.com/hugeblank/qs-cc/blob/master/src/skymodem.lua#L54)... 

In my defense, you can't blame me for skipping the "do not use this" comment for what it does. It simplifies having to scream at the user! Less screaming and more useful code.

I'm glad that this has moved somewhere more accessible.

**Comment by SquidDev** [comment]
> In my defense, you can't blame me

Well, I'm not sure who else to blame!

**Pull request merged**
