### PR TITLE
Fixed Issue #1167

### LINKED ISSUE #1167: snowy grass isn't updating
### Minecraft Version

1.18.x

### Version

1.100.9

### Details

if you move a turtle over snowy grass it will not update and wont make it too normal grass
Minecraft_ 1 18 2 - Singleplayer 12 09 2022 17_53_05

### PR DESCRIPTION
**Pull request by roland-a**
https://github.com/cc-tweaked/CC-Tweaked/issues/1167

### CODE REVIEW

**Comment by SquidDev** [comment]
Thank you very much for looking into this! I think the fix looks sensible, but I fear it's a bit too specific - it's fixing a specific symptom rather than the underlying cause.

The problem here is that we don't trigger a block update when setting the block turtle initially (the flags parameter is 0, which means do nothing).

https://github.com/cc-tweaked/CC-Tweaked/blob/c3b7302108928fa6b9920c75c28121d67dea70b3/src/main/java/dan200/computercraft/shared/turtle/core/TurtleBrain.java#L327

I think there's two solutions which might be worth trying here:
 - Change the `0` there to a `1`. This will trigger neighbour updates when the turtle is initially set. We'll want to make sure that this doesn't cause https://github.com/dan200/ComputerCraft/issues/131 to occur again though.
 - Add a call to `world.blockUpdated(pos, newState.getBlock());` after `newTurtle.updateInputsImmediately();`.

**Comment by roland-a** [comment]
I did assume it wasn't block-update related and that it was specific to snowy grass, as I saw double tall grass update when the turtle broke its top half, but not for snowy grass. Also, for some reason, neither of those two solutions fixed the issue when I added them on my workspace.

**Comment by SquidDev** [comment]
Aha, because it does the update inside `updateShape` which isn't called `blockUpdated`. Doing `world.setBlock( pos, newState, 1 )` _does_ work, but doesn't broadcast the state to the client. Changing that to `3` instead should work.

**Comment by roland-a** [comment]
Actually, flag 2 is enough to fix it.  Flag 2 is what broadcasts the state to the client.  Flag 3 is flag 1 and 2 together, which could cause the ghost block error you mentioned.

**Comment by roland-a** [comment]
The underlying cause should be fixed now.

**Review by SquidDev — APPROVED** [review]

**Comment by SquidDev** [comment]
Sorry for the delay in looking at this. Thank you very much for bearing with me :)

**Pull request merged**
