### PR TITLE
Create uk_ua.json

### PR DESCRIPTION
**Pull request by MrSvyatik**
pls adds 1.16.5 and 1.18.2

### CODE REVIEW

**Comment by Lupus590** [comment]
Translations should be submitted via Weblate. See https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.16.x/CONTRIBUTING.md#translations

**Comment by MrSvyatik** [comment]
https://i18n.tweaked.cc/projects/cc-tweaked/minecraft/uk/

**Comment by Lupus590** [comment]
I think this can be closed now.

**Comment by SquidDev** [comment]
This was merged in ca58e39707ff7d01c38fb23f3f18759590f0dd2a.

**Pull request closed without merging**
