### PR TITLE
Some input handling improvements

### PR DESCRIPTION
**Pull request by SquidDev**
- Fire `key_up`/`mouse_up` events when closing the GUI.
 - Include active modifiers in the `key` event (`"key", code, repeat, { ctrl = false, alt = true, shift = false }`).

I'm really not sure about the format of the event, whether this is a good idea, etc... so thoughts welcome!

### CODE REVIEW

**Comment by Lemmmy** [comment]
If you don't plan on adding any extra modifiers, then it might be better to use three separate booleans for the event, so that we're not throwing tables around (might be better for performance?):

```lua
local event, key, code, repeat, ctrl, alt, shift = os.pullEvent("key")
```

The table isn't too bad, though. Otherwise, this is pretty good.

**Comment by SquidDev** [comment]
Truth be told, I'm not too worried about performance here - we chuck around tables for rednet, and those are often sent far more frequently than `key` events.

**Comment by SquidDev** [comment]
I've added 7a7951ae686d3ca0614b761588fc908e5ef46f9f to master, but need to have another think about the modifiers change. There's lots of weird cases (AltGr, character events) which means you need more than a basic modifier table to implement shortcut keys accurately.

**Comment by SquidDev** [comment]
OK, I'm going to close this for now. I don't think this approach will work as a way to implement modifier keybindings. I'd like to explore some alternative approaches (such as some `key.isDown` method) in the future.

**Comment by JasonTheKitten** [comment]
I just wanted to mention that,  at least in CC 1.74, to detect keybindings with a table, key, and key_up events

**Pull request closed without merging**
