### PR TITLE
Allows to add new capabilities to turtle by upgrade

### PR DESCRIPTION
**Pull request by SirEdvin**
You can see usage example here: https://github.com/SirEdvin/ProgressivePeripherals/pull/17

### CODE REVIEW

**Comment by SirEdvin** [comment]
oh, current version contians ideological gaps, don`t review, please)

**Comment by SirEdvin** [comment]
Okey. now everything should be just fine

**Comment by SquidDev** [comment]
Apologies for taking so long to get to this. I have a lot of thoughts, and it's taken a bit of time to get them in order. I think there's a couple of things we can solve in one go here:

 - Capabilities on turtles. Aside, do we want capabilities on turtle item stacks too? It might be cool if turtles could, for instance, act as tanks in item form.
 - Persisting data when turtles are broken/placed (#847).
 - Handling additional NBT data on the upgrade `ItemStack` (we also need to handle doing this in a crafting grid).

I think the first two of these are relatively easy to solve in a cohesive manner by adding the following:

 - `interface TurtleUpgradeData extends ICapabilityProvider, INBTSerializable<Tag> { }`
 - `public TurtleUpgradeData ITurtleUpgrade.createData(ITurtleAccess, TurtleSide)`.
 - `public TurtleUpgradeData ITurtleAccess.getUpgradeData(TurtleSide)`.

I think we probably also need a generic `ITurtleAccess.setChanged()` method which just calls `TileEntity.setChanged()`.

Basically upgrades can define a class which implements `TurtleUpgradeData` and stores data about their upgrade (such as a fluid tank's contents or a list of waypoints). Those can then be persisted via `INBTSerializable<Tag>` on both the turtle block entity and item stack.

`createData` will be called before `createPeripheral`, so you can then access the constructed object when constructing your peripheral, rather than accessing it every method call.

`ICapabilityProvider` also allows this interface to expose capabilities if it wants, though those are not required.


As far as saving/reading to the upgrade item, perhaps we add two additional methods to `TurtleUpgradeData` which are basically `serializeToStack(ItemStack)` (or `ItemStack serializeToStack()`) and `deserializeFromStack(ItemStack)`?

## Example

```java
class FluidData implements TurtleUpgradeData {
  private final ITurtleAccess turtle;
  private final FluidTank current = new FluidTank();

  @Override
  public deserializeFromStack(ItemStack stack) {
    current.readFromNBT(stack.getCompoundTag().get(FLUID_TANK_TAG)); // TODO: more error checking please
  }

  // TODO: Storage and capabilities
}

class FluidUpgrade implements ITurtleUpgrade {
  @Override
  public TurtleUpgradeData createUpgradeData(ITurtleAccess turtle, TurtleSide side) {
    return new FluidData(turtle);
  }

  @Override
  public IPeripheral createPeripheral(ITurtleAccess turtle, TurtleSide side) {
    return new FluidPeripheral((FluidData)turtle.getUpgradeData(side));
  }
}
```

---

I don't know if this sounds even remotely sane?

**Comment by SirEdvin** [comment]
Sound interesting for me. If we talk about upgrade data usage, one additional problem is data syncing between client and server and as I understand, `setChanged` are not perform sync. For example, you can look [here](https://github.com/Seniorendi/AdvancedPeripherals/blob/1.16/src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/base/TurtlePeripheralOwner.java#L97) when for sync I used `playAnimation`. Maybe in additional to `setChanged` it would be nice to have something like `pushToClient`

**Comment by SquidDev** [comment]
I guess there's a few options here:

 - Add `toClientTag`/`fromClientTag` from methods to the data object, and add a `pushToClient` method as you mention. I think it makes sense to avoid sending the whole store to the client when the turtle is a BlockEntity.

 - Use `getUpgradeNBTData`/`updateUpgradeNBTData` for now (as this is synced to the client). Then when 1.17 drops rename them to something client specific and change the semantics so it's not persisted by the turtle.

**Comment by SirEdvin** [comment]
I am not sure, but now `getUpgradeNBTData` and `updateUpgradeNBTData`, if you speak about 1.16 are not automatically synced between client-server

**Comment by SquidDev** [comment]
> If you speak about 1.16 are not automatically synced between client-server

They should be - that's how modems upgrades show which state they're in.

https://github.com/SquidDev-CC/CC-Tweaked/blob/62172c60492010c392ec1b359ac67ce8c8a0cda2/src/main/java/dan200/computercraft/shared/turtle/core/TurtleBrain.java#L178-L198

**Comment by SirEdvin** [comment]
Well, from my view this methods doesn't call immediately sync, so I need to perform some sort of dirty trick like `playAnimation(None)`

**Comment by SirEdvin** [comment]
Okey, I am returning to deal! 

If you call `remove` on CompoundTag, update will not be triggered and need to be performed manually, as for 1.16 1.98.1

**Comment by SquidDev** [comment]
Updates are never triggered automatically - we can't detect mutation in the compound tag without doing an (obviously expensive) deep copy.

**Comment by SquidDev** [comment]
Closing in favour of #903.

**Pull request closed without merging**
