### PR TITLE
Fix TBO normalisation issues on old GPUs

### PR DESCRIPTION
**Pull request by Lemmmy**
This patch fixes https://github.com/Zundrel/cc-tweaked-fabric/issues/17 but will need to be tested on as many different cards as possible to ensure it works.

### CODE REVIEW

**Comment by SquidDev** [comment]
For those who have a moment to test, [a build can be downloaded from CI](https://github.com/SquidDev-CC/CC-Tweaked/suites/1374796978/artifacts/22554262).

**Comment by RubenHetKonijn** [comment]
The issue is back again :/

**Comment by Lemmmy** [comment]
You were definitely on "texture buffers" renderer when you tested the 1.12 build?

**Comment by RubenHetKonijn** [comment]
I think I had the wrong jar, im going to try again

**Comment by RubenHetKonijn** [comment]
Yes works now.

**Pull request merged**
