### PR TITLE
Add Check to delete.lua

### PR DESCRIPTION
**Pull request by JakobDev**
delete.lua checks now, if it has the permission to delete a file.

### CODE REVIEW

**Comment by JasonTheKitten** [comment]
I like this, only thing I would say is that I believe that when displaying paths most APIs and programs will ommit rom from the pathname

**Comment by JakobDev** [comment]
@JasonTheKitten It's better to use the full path. I see no reason, why we should remove the /rom part.

@lupus590 An empty string means /, which can't be deleted.

**Comment by JasonTheKitten** [comment]
Ok, I had deleted my comment, yet you still replied...

**Comment by SquidDev** [comment]
I wonder if it'd be worth doing something like this instead:

```lua
local ok, err = pcall(fs.delete, file)
if not ok then
  printError((err:gsub("^pcall: ", "")))
end
```

This way we don't need the special casing of `""`, and handle any of the weird errors that mounts may throw themselves.

I've just added the ability to [verify ROM programs produce a specific output too](https://github.com/SquidDev-CC/CC-Tweaked/blob/master/src/test/resources/test-rom/spec/programs/delete_spec.lua#L43-L46), so it might be worth writing a test for this too.

**Comment by JakobDev** [comment]
@SquidDev It use now pcall, but I don't know, how to write a test.

**Comment by JakobDev** [comment]
Closing because some problems with git. It's better to create a new branch.

**Pull request closed without merging**
